Add function to new email
CarmenMercado/mailslurp pull request #1
Opened 2022-01-19 02:47 UTC by CarmenMercado

#What
 -Add route to function to create a new email
 -Create setUp function
 -Create a new email function 
 
 #Why
 -To generate an endpoint to
<img width="1274" alt="Screen Shot 2022-01-18 at 20 35 22" src="https://user-images.githubusercontent.com/72408226/150053050-33605b2d-c164-421c-8309-0da8823c9be6.png">
 send a new email

2022-01-19 02:53 UTC, semanticmx commented
La descripción es con doble "#" para que diga ##what en lugar de #What

2022-01-19 03:00 UTC, semanticmx requested changes
va bien, solo falta estilo de PHP

2022-01-19 03:00 UTC, semanticmx commented on config/routes.yaml
> +    controller: App\Controller\MailslurpController::newEmail
hay que estandarizar los nombres, si el path es send_mail la función debe ser sendMail.

En el caso de las URL se utiliza la sintaxis kebab por ejemplo `send-mail` o puedes usar dominios por ejemplo `email/send` donde email es el dominio y send es la acción

2022-01-19 03:00 UTC, semanticmx commented on src/Controller/MailslurpController.php
> +class MailslurpController
Mail Slurp son dos palabras entonces la clase debe nombrarse `MailSlurpController` al igual que el archivo

2022-01-19 03:00 UTC, semanticmx commented on src/Controller/MailslurpController.php
> +        $inbox_controller = new InboxControllerApi(null, $this->setUp());
en PHP el nombre de las variables es camelCase, entonces se usa $inboxController en lugar de $inbox_controller como en python

2022-01-19 03:00 UTC, semanticmx commented on src/Controller/MailslurpController.php
> +        $inbox_controller = new InboxControllerApi(null, $this->setUp());
hay un "hack" que se usa en PHP para saber qué se está pasando a las funciones, por ejemplo en lugar de:

`InboxControllerApi(null, $this->setUp())`

se puede utilizar:

`InboxControllerApi($param1 = null, $config = $this->setUp())`

para que sepamos qué es cada parámetro, donde $param1 es el nombre del parámetro que espera la función

2022-01-19 20:40 UTC, CarmenMercado commented on config/routes.yaml
> +    controller: App\Controller\MailslurpController::newEmail
Okey,  lo cambio a sintaxis kebab

2022-01-19 20:41 UTC, CarmenMercado commented on src/Controller/MailslurpController.php
> +class MailslurpController
Enterada, lo cambio.

2022-01-19 20:43 UTC, CarmenMercado commented on src/Controller/MailslurpController.php
> +        $inbox_controller = new InboxControllerApi(null, $this->setUp());
Enterada, cambio las variables.

2022-01-20 01:43 UTC, semanticmx approved these changes
muy bien

2022-01-20 01:43 UTC, merged